
```{r}
countData <- read_excel("/bigrock/FurmanLab/DataRepository/promise/metabolomics/promise_metabolon_HMDB_trans.xlsx")
metaData3 <- read_excel("/bigrock/FurmanLab/DataRepository/promise/metabolomics/pre3_promise_metab_dm.xlsx")
metaData6 <- read_excel("/bigrock/FurmanLab/DataRepository/promise/metabolomics/pre6_promise_metab_dm.xlsx")
metaData9 <- read_excel("/bigrock/FurmanLab/DataRepository/promise/metabolomics/pre9_promise_metab_dm.xlsx")
countData <- countData %>% distinct(metabolite, .keep_all = TRUE)

df <- data.frame(countData)
cols <- sapply(df, is.numeric)
df[cols] <- 1000*df[cols]
head(df)
df <- cbind(df[,1], sapply(df[,-1], as.integer))
colnames(df)[1] <- "metabolite"
df <- as.data.frame(df)
head(df)
```

```{r}
# countData <- read_excel("/bigrock/FurmanLab/DataRepository/promise/metabolomics/promise_metabolon_HMDB_trans.xlsx")
countData <- read_excel("/bigrock/FurmanLab/DataRepository/promise/metabolomics/promise_metabolon_trans.xlsx")
countData <- countData[!startsWith(countData$metabolite, "X-"),]
countData  <- countData %>% distinct(metabolite, .keep_all = TRUE)

df <- data.frame(countData)
cols <- sapply(df, is.numeric)
df[cols] <- 1000*df[cols]
head(df)
df <- cbind(df[,1], sapply(df[,-1], as.integer))
colnames(df)[1] <- "metabolite"
df <- as.data.frame(df)

# Select patient samples 3 years prior to DM diagnosis
pre0_countData <- df |>
select("metabolite", 
      "X1006.0.Y3", "X1075.0.Y3", "X1131.0.Y3", "X1129.0.Y3",
      "X1177.0.Y3", "X2186.0.Y3", "X1266.0.Y6", "X2285.0.Y6", 
      "X2042.0.Y6", "X1249.0.Y6", "X2265.0.Y6", "X1150.0.Y6")

metaData0 <- data.frame (
      id  = 
      c("X1006.0.Y3", "X1075.0.Y3", "X1131.0.Y3", "X1129.0.Y3",
        "X1177.0.Y3", "X2186.0.Y3", "X1266.0.Y6", "X2285.0.Y6", 
        "X2042.0.Y6", "X1249.0.Y6", "X2265.0.Y6", "X1150.0.Y6"),
      
      Site = 
      c("Convert", "Control", "Convert", "Control",
        "Convert", "Control", "Convert", "Control",
        "Convert", "Control", "Convert", "Control"))

pre0_countData_df <- cbind(as.data.frame(pre0_countData[,1]), 
            sapply(pre0_countData[,-1], as.numeric))
colnames(pre0_countData_df)[1] <- "metabolite"
pre0_countData <- as.data.frame(pre0_countData_df)
pre0_countData   <- pre0_countData  |> na.omit()
write_csv(pre0_countData, 
          file = "/bigrock/FurmanLab/DataRepository/promise/metabolomics/Pre0_metabolomics.csv")
# write_csv(pre0_countData, 
#          file = "/bigrock/FurmanLab/DataRepository/promise/metabolomics/Pre0_metabolomics_HMDB.csv")

# Differential metabolites
countData <- as.data.frame(pre0_countData)
metaData <- as.data.frame(metaData0)
dds <- DESeqDataSetFromMatrix(countData=countData, colData=metaData, design=~Site, tidy = TRUE)
dds <- DESeq(dds)
res <- results(dds)
DEGs <- results(dds, contrast=c("Site","Convert", "Control"))

# All Differential  metabolites
DEGs_sig_all <- subset(DEGs, pvalue <= 0.05)
DEGs_sig_all <- as.data.frame(DEGs_sig_all)
DEGs_sig_all$protein <- rownames(DEGs_sig_all)
 write_csv(DEGs_sig_all, 
            file = "/bigrock/FurmanLab/DataRepository/promise/metabolomics/Pre0_DEM_all.csv")
# write_csv(DEGs_sig_all, 
#          file = "/bigrock/FurmanLab/DataRepository/promise/metabolomics/Pre0_DEM_all_HMDB.csv")

# Up-regulated Metabolites
DEGs_sig_up <- subset(DEGs, pvalue <= 0.05 & log2FoldChange >= 0)
DEGs_sig_up <- as.data.frame(DEGs_sig_up)
DEGs_sig_up$metabolite <- rownames(DEGs_sig_up)
DEGs_sig_up <- DEGs_sig_up |> select("metabolite")
write_csv(DEGs_sig_up, 
          file = "/bigrock/FurmanLab/DataRepository/promise/metabolomics/Pre0_DEM_up.csv")
# write_csv(DEGs_sig_up, 
#          file = "/bigrock/FurmanLab/DataRepository/promise/metabolomics/Pre0_DEM_up_HMDB.csv")

# Down-regulated Metabolites
DEGs_sig_down <- subset(DEGs, pvalue <= 0.05 & log2FoldChange <= 0)
DEGs_sig_down <- as.data.frame(DEGs_sig_down)
DEGs_sig_down$metabolite <- rownames(DEGs_sig_down)
DEGs_sig_down <- DEGs_sig_down |> select("metabolite")
write_csv(DEGs_sig_down, 
          file = "/bigrock/FurmanLab/DataRepository/promise/metabolomics/Pre0_DEM_down.csv")
# write_csv(DEGs_sig_down, 
#          file = "/bigrock/FurmanLab/DataRepository/promise/metabolomics/Pre0_DEM_down_HMDB.csv")
```

```{r}
# countData <- read_excel("/bigrock/FurmanLab/DataRepository/promise/metabolomics/promise_metabolon_HMDB_trans.xlsx")
countData <- read_excel("/bigrock/FurmanLab/DataRepository/promise/metabolomics/promise_metabolon_trans.xlsx")
countData <- countData[!startsWith(countData$metabolite, "X-"),]
countData  <- countData %>% distinct(metabolite, .keep_all = TRUE)

df <- data.frame(countData)
cols <- sapply(df, is.numeric)
df[cols] <- 1000*df[cols]
head(df)
df <- cbind(df[,1], sapply(df[,-1], as.integer))
colnames(df)[1] <- "metabolite"
df <- as.data.frame(df)

# Select patient samples 3 years prior to DM diagnosis
pre3_countData <- df |>
select("metabolite", 
       "X1131.0.Y0", "X1129.0.Y0", "X1152.0.Y6", "X2220.0.Y6", 
       "X1177.0.Y0", "X2186.0.Y0", "X1266.0.Y3", "X2285.0.Y3", 
       "X1300.0.Y6", "X2070.0.Y6", "X1397.0.Y6", "X2261.0.Y6",
       "X2042.0.Y3", "X1249.0.Y3", "X2089.0.Y6", "X2280.0.Y6")

metaData3 <- data.frame (
      id  = 
      c("X1131.0.Y0", "X1129.0.Y0", "X1152.0.Y6", "X2220.0.Y6", 
        "X1177.0.Y0", "X2186.0.Y0", "X1266.0.Y3", "X2285.0.Y3", 
        "X1300.0.Y6", "X2070.0.Y6", "X1397.0.Y6", "X2261.0.Y6",
        "X2042.0.Y3", "X1249.0.Y3", "X2089.0.Y6", "X2280.0.Y6"),
      Site = 
      c("Convert", "Control", "Convert", "Control",
        "Convert", "Control", "Convert", "Control", 
        "Convert", "Control", "Convert", "Control", 
        "Convert", "Control", "Convert", "Control"))

pre3_countData_df <- cbind(as.data.frame(pre3_countData[,1]), 
            sapply(pre3_countData[,-1], as.numeric))
colnames(pre3_countData_df)[1] <- "metabolite"
pre3_countData <- as.data.frame(pre3_countData_df)
pre3_countData   <- pre3_countData  |> na.omit()
write_csv(pre3_countData, 
          file = "/bigrock/FurmanLab/DataRepository/promise/metabolomics/Pre3_metabolomics.csv")
# write_csv(pre3_countData, 
#          file = "/bigrock/FurmanLab/DataRepository/promise/metabolomics/Pre3_metabolomics_HMDB.csv")

# Differential metabolites
countData <- as.data.frame(pre3_countData)
metaData <- as.data.frame(metaData3)
dds <- DESeqDataSetFromMatrix(countData=countData, colData=metaData, design=~Site, tidy = TRUE)
dds <- DESeq(dds)
res <- results(dds)
DEGs <- results(dds, contrast=c("Site","Convert", "Control"))

# All Differential  metabolites
DEGs_sig_all <- subset(DEGs, pvalue <= 0.05)
DEGs_sig_all <- as.data.frame(DEGs_sig_all)
DEGs_sig_all$protein <- rownames(DEGs_sig_all)
write_csv(DEGs_sig_all, 
            file = "/bigrock/FurmanLab/DataRepository/promise/metabolomics/Pre3_DEM_all.csv")
# write_csv(DEGs_sig_all, 
#            file = "/bigrock/FurmanLab/DataRepository/promise/metabolomics/Pre3_DEM_all_HMDB.csv")

# Up-regulated Metabolites
DEGs_sig_up <- subset(DEGs, pvalue <= 0.05 & log2FoldChange >= 0)
DEGs_sig_up <- as.data.frame(DEGs_sig_up)
DEGs_sig_up$metabolite <- rownames(DEGs_sig_up)
DEGs_sig_up <- DEGs_sig_up |> select("metabolite")
write_csv(DEGs_sig_up, 
          file = "/bigrock/FurmanLab/DataRepository/promise/metabolomics/Pre3_DEM_up.csv")
# write_csv(DEGs_sig_up, 
#         file = "/bigrock/FurmanLab/DataRepository/promise/metabolomics/Pre3_DEM_up_HMDB.csv")

# Down-regulated Metabolites
DEGs_sig_down <- subset(DEGs, pvalue <= 0.05 & log2FoldChange <= 0)
DEGs_sig_down <- as.data.frame(DEGs_sig_down)
DEGs_sig_down$metabolite <- rownames(DEGs_sig_down)
DEGs_sig_down <- DEGs_sig_down |> select("metabolite")
write_csv(DEGs_sig_down, 
          file = "/bigrock/FurmanLab/DataRepository/promise/metabolomics/Pre3_DEM_down.csv")
# write_csv(DEGs_sig_down, 
#          file = "/bigrock/FurmanLab/DataRepository/promise/metabolomics/Pre3_DEM_down_HMDB.csv")
```


```{r}
# countData <- read_excel("/bigrock/FurmanLab/DataRepository/promise/metabolomics/promise_metabolon_HMDB_trans.xlsx")
countData <- read_excel("/bigrock/FurmanLab/DataRepository/promise/metabolomics/promise_metabolon_trans.xlsx")
countData <- countData[!startsWith(countData$metabolite, "X-"),]
countData  <- countData %>% distinct(metabolite, .keep_all = TRUE)

df <- data.frame(countData)
cols <- sapply(df, is.numeric)
df[cols] <- 1000*df[cols]
head(df)
df <- cbind(df[,1], sapply(df[,-1], as.integer))
colnames(df)[1] <- "metabolite"
df <- as.data.frame(df)

# Select patient samples 6 years prior to DM diagnosis
pre6_countData <- df |>
select("metabolite", 
       "X1152.0.Y3", "X2220.0.Y3", "X1266.0.Y0", "X2285.0.Y0", 
       "X1300.0.Y3", "X2070.0.Y3", "X1397.0.Y3", "X2261.0.Y3", 
       "X2042.0.Y0", "X1249.0.Y0", "X2099.0.Y3", "X2089.0.Y3",
       "X2127.0.Y3", "X2280.0.Y3", "X2265.0.Y0", "X1150.0.Y0", 
       "X2321.0.Y3", "X2249.0.Y3")

metaData6 <- data.frame (
      id  = 
      c("X1152.0.Y3", "X2220.0.Y3", "X1266.0.Y0", "X2285.0.Y0", 
        "X1300.0.Y3", "X2070.0.Y3", "X1397.0.Y3", "X2261.0.Y3", 
        "X2042.0.Y0", "X1249.0.Y0", "X2099.0.Y3", "X2089.0.Y3",
        "X2127.0.Y3", "X2280.0.Y3", "X2265.0.Y0", "X1150.0.Y0", 
        "X2321.0.Y3", "X2249.0.Y3"),
      
      Site = 
      c("Convert", "Control", "Convert", "Control",
        "Convert", "Control","Convert", "Control", 
        "Convert", "Control", "Convert", "Control", 
        "Convert", "Control", "Convert", "Control",
        "Convert", "Control"))

pre6_countData_df <- cbind(as.data.frame(pre6_countData[,1]), 
            sapply(pre6_countData[,-1], as.numeric))
colnames(pre6_countData_df)[1] <- "metabolite"
pre6_countData <- as.data.frame(pre6_countData_df)
pre6_countData   <- pre6_countData  |> na.omit()
# write_csv(pre6_countData, 
#          file = "/bigrock/FurmanLab/DataRepository/promise/metabolomics/Pre6_metabolomics_HMDB.csv")
write_csv(pre6_countData, 
          file = "/bigrock/FurmanLab/DataRepository/promise/metabolomics/Pre6_metabolomics.csv")

# Differential metabolites
countData <- as.data.frame(pre6_countData)
metaData <- as.data.frame(metaData6)
dds <- DESeqDataSetFromMatrix(countData=countData, colData=metaData, design=~Site, tidy = TRUE)
dds <- DESeq(dds)
res <- results(dds)
DEGs <- results(dds, contrast=c("Site","Convert", "Control"))

# All Differential Proteins
DEGs_sig_all <- subset(DEGs, pvalue <= 0.05)
DEGs_sig_all <- as.data.frame(DEGs_sig_all)
DEGs_sig_all$protein <- rownames(DEGs_sig_all)
# write_csv(DEGs_sig_all, 
#          file = "/bigrock/FurmanLab/DataRepository/promise/metabolomics/Pre6_DEM_all_HMDB.csv")
write_csv(DEGs_sig_all, 
          file = "/bigrock/FurmanLab/DataRepository/promise/metabolomics/Pre6_DEM_all.csv")

# Up-regulated Metabolites
DEGs_sig_up <- subset(DEGs, pvalue <= 0.05 & log2FoldChange >= 0)
DEGs_sig_up <- as.data.frame(DEGs_sig_up)
DEGs_sig_up$metabolite <- rownames(DEGs_sig_up)
DEGs_sig_up <- DEGs_sig_up |> select("metabolite")
# write_csv(DEGs_sig_up, 
#          file = "/bigrock/FurmanLab/DataRepository/promise/metabolomics/Pre6_DEM_up_HMDB.csv")
write_csv(DEGs_sig_up, 
          file = "/bigrock/FurmanLab/DataRepository/promise/metabolomics/Pre6_DEM_up.csv")

# Down-regulated Metabolites
DEGs_sig_down <- subset(DEGs, pvalue <= 0.05 & log2FoldChange <= 0)
DEGs_sig_down <- as.data.frame(DEGs_sig_down)
DEGs_sig_down$metabolite <- rownames(DEGs_sig_down)
DEGs_sig_down <- DEGs_sig_down |> select("metabolite")
# write_csv(DEGs_sig_down, 
#          file = "/bigrock/FurmanLab/DataRepository/promise/metabolomics/Pre6_DEM_down_HMDB.csv")
write_csv(DEGs_sig_down, 
          file = "/bigrock/FurmanLab/DataRepository/promise/metabolomics/Pre6_DEM_down.csv")
```

```{r}
# countData <- read_excel("/bigrock/FurmanLab/DataRepository/promise/metabolomics/promise_metabolon_HMDB_trans.xlsx")
countData <- read_excel("/bigrock/FurmanLab/DataRepository/promise/metabolomics/promise_metabolon_trans.xlsx")
countData <- countData[!startsWith(countData$metabolite, "X-"),]
countData  <- countData %>% distinct(metabolite, .keep_all = TRUE)

df <- data.frame(countData)
cols <- sapply(df, is.numeric)
df[cols] <- 1000*df[cols]
head(df)
df <- cbind(df[,1], sapply(df[,-1], as.integer))
colnames(df)[1] <- "metabolite"
df <- as.data.frame(df)


# Select patient samples 9 years prior to DM diagnosis
pre9_countData <- df |>
select("metabolite", 
       "X1300.0.Y0", "X2070.0.Y0", "X1397.0.Y0", "X2261.0.Y0",
       "X2099.0.Y0", "X2089.0.Y0", "X2127.0.Y0", "X2280.0.Y0", 
       "X2321.0.Y0", "X2249.0.Y0")

metaData9 <- data.frame (
      id  = 
      c("X1300.0.Y0", "X2070.0.Y0", "X1397.0.Y0", "X2261.0.Y0",
        "X2099.0.Y0", "X2089.0.Y0", "X2127.0.Y0", "X2280.0.Y0", 
        "X2321.0.Y0", "X2249.0.Y0"),
      
      Site = 
      c("Convert", "Control", "Convert", "Control",
        "Convert", "Control", "Convert", "Control", 
        "Convert", "Control"))

df <- cbind(as.data.frame(pre9_countData[,1]), 
            sapply(pre9_countData[,-1], as.numeric))
colnames(df)[1] <- "metabolite"
pre9_countData <- as.data.frame(df)
pre9_countData   <- pre9_countData  |> na.omit()
# write_csv(pre9_countData, 
#          file = "/bigrock/FurmanLab/DataRepository/promise/metabolomics/Pre9_metabolomics_HMDB.csv")
write_csv(pre9_countData, 
          file = "/bigrock/FurmanLab/DataRepository/promise/metabolomics/Pre9_metabolomics.csv")

# Differential metabolites
countData <- as.data.frame(pre9_countData)
metaData <- as.data.frame(metaData9)
dds <- DESeqDataSetFromMatrix(countData=countData, colData=metaData, design=~Site, tidy = TRUE)
dds <- DESeq(dds)
res <- results(dds)
DEGs <- results(dds, contrast=c("Site","Convert", "Control"))

# All Differential Proteins
DEGs_sig_all <- subset(DEGs, pvalue <= 0.05)
DEGs_sig_all <- as.data.frame(DEGs_sig_all)
DEGs_sig_all$protein <- rownames(DEGs_sig_all)
# write_csv(DEGs_sig_all, 
#          file = "/bigrock/FurmanLab/DataRepository/promise/metabolomics/Pre9_DEM_all_HMDB.csv")
write_csv(DEGs_sig_all, 
          file = "/bigrock/FurmanLab/DataRepository/promise/metabolomics/Pre9_DEM_all.csv")

# Up-regulated Metabolites
DEGs_sig_up <- subset(DEGs, pvalue <= 0.05 & log2FoldChange >= 0)
DEGs_sig_up <- as.data.frame(DEGs_sig_up)
DEGs_sig_up$metabolite <- rownames(DEGs_sig_up)
DEGs_sig_up <- DEGs_sig_up |> select("metabolite")
# write_csv(DEGs_sig_up, 
#          file = "/bigrock/FurmanLab/DataRepository/promise/metabolomics/Pre9_DEM_up_HMDB.csv")
write_csv(DEGs_sig_up, 
          file = "/bigrock/FurmanLab/DataRepository/promise/metabolomics/Pre9_DEM_up.csv")

# Down-regulated Metabolites
DEGs_sig_down <- subset(DEGs, pvalue <= 0.05 & log2FoldChange <= 0)
DEGs_sig_down <- as.data.frame(DEGs_sig_down)
DEGs_sig_down$metabolite <- rownames(DEGs_sig_down)
DEGs_sig_down <- DEGs_sig_down |> select("metabolite")
# write_csv(DEGs_sig_down, 
#          file = "/bigrock/FurmanLab/DataRepository/promise/metabolomics/Pre9_DEM_down_HMDB.csv")
write_csv(DEGs_sig_down, 
          file = "/bigrock/FurmanLab/DataRepository/promise/metabolomics/Pre9_DEM_down.csv")
```





